version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
