version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types:
          - "patch"
          - "minor"
