main = "src/index.ts"
compatibility_date = "2023-08-01"
workers_dev = true
account_id = "ac4880feb8f60847f0577d5967bf2b59"
find_additional_modules = true
rules = [
  { type = "ESModule", globs = ["src/commands/*.ts", "src/services/*.ts"], fallthrough = true }
]

[env.dev]
name = "discord-worker-dev"
kv_namespaces = [
    { binding = "KV", id ="4000434490424208b40ea5817cf0f86e", preview_id = "4000434490424208b40ea5817cf0f86e" }
]
upload_source_maps = true
[env.dev.vars]
SKIP_SIGNATURE_CHECK = "true"

[env.test]
name = "discord-worker-test"
kv_namespaces = [
    { binding = "KV", id = "f7b9e2cbd87640a286eb71509304ce9b" }
]
upload_source_maps = true

[env.prod]
name = "discord-worker"
kv_namespaces = [
    { binding = "KV", id = "1ac499a14b8345f0b30a7f526b9df6b9" }
]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_GUILD_ID
