main = "src/index.ts"
compatibility_date = "2025-08-27"
workers_dev = true
account_id = "ac4880feb8f60847f0577d5967bf2b59"
find_additional_modules = true
rules = [
    { type = "ESModule", globs = ["src/commands/**/*.ts", "src/services/**/*.ts", "src/generated/**/*.ts"], fallthrough = true }
]

[env.dev]
name = "discord-worker-dev"
kv_namespaces = [
    { binding = "KV", id ="4000434490424208b40ea5817cf0f86e", preview_id = "4000434490424208b40ea5817cf0f86e" }
]
secrets_store_secrets = [
    { binding = "REDDIT_APPLICATION_ID", store_id = "bcfe20a10506483d95a91e302bd42d41", secret_name = "REDDIT_APPLICATION_ID" },
    { binding = "REDDIT_TOKEN", store_id = "bcfe20a10506483d95a91e302bd42d41", secret_name = "REDDIT_TOKEN" },
]
upload_source_maps = true
remote = true

[env.dev.vars]
DISCORD_APPLICATION_ID = "TEST_APPLICATION"
DISCORD_TOKEN = "not-a-real-token"
SIGNATURE_PUBLIC_KEY = "04762816e9bab4e08bfcce909351a221ca8f7751affa16ef757881eba6560d1e"
DISCORD_URL = "https://discord.com/api/v10"
REDDIT_URL = "https://oauth.reddit.com"
OPENDOTA_URL = "https://api.opendota.com/api"

[env.test]
name = "discord-worker-test"
kv_namespaces = [
    { binding = "KV", id = "f7b9e2cbd87640a286eb71509304ce9b" }
]
secrets_store_secrets = [
    { binding = "REDDIT_APPLICATION_ID", store_id = "bcfe20a10506483d95a91e302bd42d41", secret_name = "REDDIT_APPLICATION_ID" },
    { binding = "REDDIT_TOKEN", store_id = "bcfe20a10506483d95a91e302bd42d41", secret_name = "REDDIT_TOKEN" },
]

[env.test.vars]
DISCORD_APPLICATION_ID = "TEST_APPLICATION"
DISCORD_TOKEN = "not-a-real-token"
SIGNATURE_PUBLIC_KEY = "d392fc518bebf4dbc2fc3f7dead4237f87b60bb1d7bbd57a2a91a05da5003a26"
DISCORD_URL = "https://discord.com/api/v10"
REDDIT_URL = "https://oauth.reddit.com"
OPENDOTA_URL = "https://api.opendota.com/api"

[env.prod]
name = "discord-worker"
kv_namespaces = [
    { binding = "KV", id = "1ac499a14b8345f0b30a7f526b9df6b9" }
]
secrets_store_secrets = [
    { binding = "REDDIT_APPLICATION_ID", store_id = "bcfe20a10506483d95a91e302bd42d41", secret_name = "REDDIT_APPLICATION_ID" },
    { binding = "REDDIT_TOKEN", store_id = "bcfe20a10506483d95a91e302bd42d41", secret_name = "REDDIT_TOKEN" },
]

# [secrets]
# SIGNATURE_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# DISCORD_TOKEN
