on:
  push:
    branches:
      - main
name: ci
permissions:
  contents: read
concurrency:
  group: test-release
  cancel-in-progress: false
jobs:
  release-test:
    uses: ./.github/workflows/deploy-env.yaml
    with:
      environment_name: test
      publish_script: publish:test
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
