on:
  push:
    branches:
      - main
name: ci
permissions:
  contents: read
concurrency:
  group: test-release
  cancel-in-progress: false
jobs:
  test-release:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm run publish:test
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - run: npm run deploy_commands
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
