on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      publish_script:
        required: true
        type: string
      git_ref:
        required: false
        type: string
        default: ''
    secrets:
      CF_API_TOKEN:
        required: true
      CF_ACCOUNT_ID:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - if: ${{ inputs.git_ref == '' }}
        uses: actions/checkout@v6.0.2
      - if: ${{ inputs.git_ref != '' }}
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ inputs.git_ref }}
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm run ${{ inputs.publish_script }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

  post-release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    needs: [release]
    steps:
      - if: ${{ inputs.git_ref == '' }}
        uses: actions/checkout@v6.0.2
      - if: ${{ inputs.git_ref != '' }}
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ inputs.git_ref }}
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm run deploy_commands
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
